/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as SessionsIdRouteImport } from './routes/sessions/$id'
import { Route as LoginPlaytomicRouteImport } from './routes/login/playtomic'
import { Route as LoginOtpRouteImport } from './routes/login/otp'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp-webhook'
import { Route as SessionsIdMatchIdRouteImport } from './routes/sessions/$id.$matchId'
import { Route as ApiSyncMatchPublicMatchIdRouteImport } from './routes/api/sync-match.$publicMatchId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPlaytomicRoute = LoginPlaytomicRouteImport.update({
  id: '/login/playtomic',
  path: '/login/playtomic',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/login/otp',
  path: '/login/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdMatchIdRoute = SessionsIdMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => SessionsIdRoute,
} as any)
const ApiSyncMatchPublicMatchIdRoute =
  ApiSyncMatchPublicMatchIdRouteImport.update({
    id: '/api/sync-match/$publicMatchId',
    path: '/api/sync-match/$publicMatchId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/login/otp': typeof LoginOtpRoute
  '/login/playtomic': typeof LoginPlaytomicRoute
  '/sessions/$id': typeof SessionsIdRouteWithChildren
  '/sessions/new': typeof SessionsNewRoute
  '/login': typeof LoginIndexRoute
  '/api/sync-match/$publicMatchId': typeof ApiSyncMatchPublicMatchIdRoute
  '/sessions/$id/$matchId': typeof SessionsIdMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/login/otp': typeof LoginOtpRoute
  '/login/playtomic': typeof LoginPlaytomicRoute
  '/sessions/$id': typeof SessionsIdRouteWithChildren
  '/sessions/new': typeof SessionsNewRoute
  '/login': typeof LoginIndexRoute
  '/api/sync-match/$publicMatchId': typeof ApiSyncMatchPublicMatchIdRoute
  '/sessions/$id/$matchId': typeof SessionsIdMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/login/otp': typeof LoginOtpRoute
  '/login/playtomic': typeof LoginPlaytomicRoute
  '/sessions/$id': typeof SessionsIdRouteWithChildren
  '/sessions/new': typeof SessionsNewRoute
  '/login/': typeof LoginIndexRoute
  '/api/sync-match/$publicMatchId': typeof ApiSyncMatchPublicMatchIdRoute
  '/sessions/$id/$matchId': typeof SessionsIdMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/api/whatsapp-webhook'
    | '/login/otp'
    | '/login/playtomic'
    | '/sessions/$id'
    | '/sessions/new'
    | '/login'
    | '/api/sync-match/$publicMatchId'
    | '/sessions/$id/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/api/whatsapp-webhook'
    | '/login/otp'
    | '/login/playtomic'
    | '/sessions/$id'
    | '/sessions/new'
    | '/login'
    | '/api/sync-match/$publicMatchId'
    | '/sessions/$id/$matchId'
  id:
    | '__root__'
    | '/'
    | '/logout'
    | '/api/whatsapp-webhook'
    | '/login/otp'
    | '/login/playtomic'
    | '/sessions/$id'
    | '/sessions/new'
    | '/login/'
    | '/api/sync-match/$publicMatchId'
    | '/sessions/$id/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogoutRoute: typeof LogoutRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  LoginOtpRoute: typeof LoginOtpRoute
  LoginPlaytomicRoute: typeof LoginPlaytomicRoute
  SessionsIdRoute: typeof SessionsIdRouteWithChildren
  SessionsNewRoute: typeof SessionsNewRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiSyncMatchPublicMatchIdRoute: typeof ApiSyncMatchPublicMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/playtomic': {
      id: '/login/playtomic'
      path: '/login/playtomic'
      fullPath: '/login/playtomic'
      preLoaderRoute: typeof LoginPlaytomicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/otp': {
      id: '/login/otp'
      path: '/login/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/$matchId': {
      id: '/sessions/$id/$matchId'
      path: '/$matchId'
      fullPath: '/sessions/$id/$matchId'
      preLoaderRoute: typeof SessionsIdMatchIdRouteImport
      parentRoute: typeof SessionsIdRoute
    }
    '/api/sync-match/$publicMatchId': {
      id: '/api/sync-match/$publicMatchId'
      path: '/api/sync-match/$publicMatchId'
      fullPath: '/api/sync-match/$publicMatchId'
      preLoaderRoute: typeof ApiSyncMatchPublicMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessionsIdRouteChildren {
  SessionsIdMatchIdRoute: typeof SessionsIdMatchIdRoute
}

const SessionsIdRouteChildren: SessionsIdRouteChildren = {
  SessionsIdMatchIdRoute: SessionsIdMatchIdRoute,
}

const SessionsIdRouteWithChildren = SessionsIdRoute._addFileChildren(
  SessionsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogoutRoute: LogoutRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  LoginOtpRoute: LoginOtpRoute,
  LoginPlaytomicRoute: LoginPlaytomicRoute,
  SessionsIdRoute: SessionsIdRouteWithChildren,
  SessionsNewRoute: SessionsNewRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiSyncMatchPublicMatchIdRoute: ApiSyncMatchPublicMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
