"use strict";
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.routeTree = void 0;
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
var __root_1 = require("./routes/__root");
var logout_1 = require("./routes/logout");
var index_1 = require("./routes/index");
var index_2 = require("./routes/login/index");
var new_1 = require("./routes/sessions/new");
var _id_1 = require("./routes/sessions/$id");
var playtomic_1 = require("./routes/login/playtomic");
var otp_1 = require("./routes/login/otp");
var _id__matches_1 = require("./routes/sessions/$id_.matches");
var LogoutRoute = logout_1.Route.update({
    id: '/logout',
    path: '/logout',
    getParentRoute: function () { return __root_1.Route; },
});
var IndexRoute = index_1.Route.update({
    id: '/',
    path: '/',
    getParentRoute: function () { return __root_1.Route; },
});
var LoginIndexRoute = index_2.Route.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: function () { return __root_1.Route; },
});
var SessionsNewRoute = new_1.Route.update({
    id: '/sessions/new',
    path: '/sessions/new',
    getParentRoute: function () { return __root_1.Route; },
});
var SessionsIdRoute = _id_1.Route.update({
    id: '/sessions/$id',
    path: '/sessions/$id',
    getParentRoute: function () { return __root_1.Route; },
});
var LoginPlaytomicRoute = playtomic_1.Route.update({
    id: '/login/playtomic',
    path: '/login/playtomic',
    getParentRoute: function () { return __root_1.Route; },
});
var LoginOtpRoute = otp_1.Route.update({
    id: '/login/otp',
    path: '/login/otp',
    getParentRoute: function () { return __root_1.Route; },
});
var SessionsIdMatchesRoute = _id__matches_1.Route.update({
    id: '/sessions/$id_/matches',
    path: '/sessions/$id/matches',
    getParentRoute: function () { return __root_1.Route; },
});
var rootRouteChildren = {
    IndexRoute: IndexRoute,
    LogoutRoute: LogoutRoute,
    LoginOtpRoute: LoginOtpRoute,
    LoginPlaytomicRoute: LoginPlaytomicRoute,
    SessionsIdRoute: SessionsIdRoute,
    SessionsNewRoute: SessionsNewRoute,
    LoginIndexRoute: LoginIndexRoute,
    SessionsIdMatchesRoute: SessionsIdMatchesRoute,
};
exports.routeTree = __root_1.Route
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
